<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OpenRecruitmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $recruitmentData = [
            [
                'nama_lengkap' => 'Abdel Raindy Andrian Zakaria',
                'email' => 'abdel.raindy.andrian.zakaria.te25@stu.pnj.ac.id',
                'no_hp' => '082113321479',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Abdullah Luthfi Al Rasyid',
                'email' => 'abdullah.luthfi.al.rasyid.te25@stu.pnj.ac.id',
                'no_hp' => '081276278832',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Abinaya Bisma Wiratama',
                'email' => 'abhinayabisma3012@gmail.com',
                'no_hp' => '089516774053',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Abrisam Rasyid',
                'email' => 'abrisam.rasyid.te25@stu.pnj.ac.id',
                'no_hp' => '085122958471',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Achmad Syaechu',
                'email' => 'achmad.syaechu.te25@stu.pnj.ac.id',
                'no_hp' => '081586624207',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Adam Rizky Rahmadan',
                'email' => 'adam.rizky.rahmadan.tik25@stu.pnj.ac.id',
                'no_hp' => '0895360846102',
                'jurusan_prodi_kelas' => 'TIK/TI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Adira Prawira Wijaya',
                'email' => 'adira.prawira.wijaya.te25@stu.pnj.ac.id',
                'no_hp' => '087763072507',
                'jurusan_prodi_kelas' => 'TE/TOLI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Adrian Hosea',
                'email' => 'adrian.hosea.te25@stu.pnj.ac.id',
                'no_hp' => '085695039312',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ahmad Haidar Alkhoiri',
                'email' => 'ahmad.haidar.alkhoiri.te25@stu.pnj.ac.id',
                'no_hp' => '089675971651',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ahmad Zaki Ghani',
                'email' => 'ahmad.zaki.ghani.te24@stu.pnj.ac.id',
                'no_hp' => '089503671594',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ahmad Zidan',
                'email' => 'salmidandidinda@gmail.com',
                'no_hp' => '0881012223639',
                'jurusan_prodi_kelas' => 'TM/TRM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'ailsa talitha nur maryam',
                'email' => 'ailsa.maryam28@gmail.com',
                'no_hp' => '085719720469',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Alfian Randy',
                'email' => 'alfian.randy.te25@stu.pnj.ac.id',
                'no_hp' => '089508350068',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Alfiana Cyndie Rahmadhani',
                'email' => 'alfiana.cyndie.rahmadhani.tik25@stu.pnj.ac.id',
                'no_hp' => '081398177609',
                'jurusan_prodi_kelas' => 'TIK/TI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Alif Ammar Fathurrahman',
                'email' => 'alif.ammar.fathurrahman.te25@stu.pnj.ac.id',
                'no_hp' => '087824012406',
                'jurusan_prodi_kelas' => 'TE/TL/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Alif Rizaldy Azra',
                'email' => 'alif.rizaldy.azra.ak25@stu.pnj.ac.id',
                'no_hp' => '085695748343',
                'jurusan_prodi_kelas' => 'TAK/BKT/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Amili Putri',
                'email' => 'amili.putri.ak25@stu.pnj.ac.id',
                'no_hp' => '085649840274',
                'jurusan_prodi_kelas' => 'TAK/BKT/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Amir Abdillah',
                'email' => 'amir.abdillah.te25@stu.pnj.ac.id',
                'no_hp' => '087788344748',
                'jurusan_prodi_kelas' => 'TE/TOLI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ananta Adya Putra Nugroho',
                'email' => 'ananta.adya.putra.nugroho.ak25@stu.pnj.ac.id',
                'no_hp' => '085693432152',
                'jurusan_prodi_kelas' => 'TAK/BKT/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Anindya Putri',
                'email' => 'anindya.putri.tik25@stu.pnj.ac.id',
                'no_hp' => '081324661670',
                'jurusan_prodi_kelas' => 'TIK/TI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Aqilla Daffaryan Satria Putra',
                'email' => 'aqilladapa12@gmail.com',
                'no_hp' => '087761606456',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Arsya Fatwa Ardina',
                'email' => 'arsya.fatwa.ardina.ak25@stu.pnj.ac.id',
                'no_hp' => '083152930884',
                'jurusan_prodi_kelas' => 'TAK/BKT/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Audia Rizky Kusuma',
                'email' => 'audia.rizky.kusuma.te25@stu.pnj.ac.id',
                'no_hp' => '085810003427',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Azga Syahraz Arditha',
                'email' => 'azga.syahraz.arditha.te25@stu.pnj.ac.id',
                'no_hp' => '085198680234',
                'jurusan_prodi_kelas' => 'TE/BM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Azka Maulidia',
                'email' => 'azka.maulidia.ak25@stu.pnj.ac.id',
                'no_hp' => '085814511292',
                'jurusan_prodi_kelas' => 'TAK/BKT/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Bintang putra adryan',
                'email' => 'bintang.putra.adryan.tik25@stu.pnj.ac.id',
                'no_hp' => '081384538695',
                'jurusan_prodi_kelas' => 'TIK/TI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'BUDI LUTVI HAKIM',
                'email' => 'budi.lutvi.hakim.te25@stu.pnj.ac.id',
                'no_hp' => '081290722307',
                'jurusan_prodi_kelas' => 'TE/TOLI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Chalid Nazwa El Azmi',
                'email' => 'chalid.nazwa.el.azmi.te25@stu.pnj.ac.id',
                'no_hp' => '083180130495',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Danendra Althaf',
                'email' => 'danendra.althaf.te25@stu.pnj.ac.id',
                'no_hp' => '081295675033',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Dante Gavriello Stevano',
                'email' => 'dante.gavriello.stevano.te23@stu.pnj.ac.id',
                'no_hp' => '08988366008',
                'jurusan_prodi_kelas' => 'TE/IKI/6B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Davino Adinata Nugroho',
                'email' => 'davino.adinata.nugroho.te25@stu.pnj.ac.id',
                'no_hp' => '087836324797',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Dhani Wira Saputra',
                'email' => 'dhani.wira.saputra.tik25@stu.pnj.ac.id',
                'no_hp' => '089525244866',
                'jurusan_prodi_kelas' => 'TIK/TI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Dhia Eka Putri',
                'email' => 'dhia.eka.putri.te25@stu.pnj.ac.id',
                'no_hp' => '085142021607',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Dwi Nur Aprilia',
                'email' => 'dwi.nur.aprilia.te25@stu.pnj.ac.id',
                'no_hp' => '089516185872',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'FABIOLA YUNANSIO PUTRI HARTANA',
                'email' => 'fabiolayphh@gmail.com',
                'no_hp' => '0812899796541',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fachri Al-Shaleh',
                'email' => 'fachri.alshaleh.tm25@stu.pnj.ac.id',
                'no_hp' => '083874965168',
                'jurusan_prodi_kelas' => 'TM/TM/2E',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fadillah Ar-Rosuli',
                'email' => 'fadillah.ar.rosuli.te24@stu.pnj.ac.id',
                'no_hp' => '088808357735',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fadli Muhammad At Thariq',
                'email' => 'fadli.muhammad.at.thariq.tm25@stu.pnj.ac.id',
                'no_hp' => '085691666207',
                'jurusan_prodi_kelas' => 'TM/ME/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fadli Rifqi Aziz',
                'email' => 'fadli.rifqi.aziz.te25@stu.pnj.ac.id',
                'no_hp' => '082325177971',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fahmi Firdaus',
                'email' => 'fahmi.firdaus.te24@stu.pnj.ac.id',
                'no_hp' => '085771501298',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Faira Izzati Nasution',
                'email' => 'fairaizztnastn1277@gmail.com',
                'no_hp' => '08974556745',
                'jurusan_prodi_kelas' => 'TM/TRKE/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Faisal Man Ali Daniyal',
                'email' => 'faisal.man.ali.daniyal.te25@stu.pnj.ac.id',
                'no_hp' => '088298287453',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fakhri Ramadhan',
                'email' => 'fakhri.ramadhan.te25@stu.pnj.ac.id',
                'no_hp' => '085758450426',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Farid Dhaffa Musyyafa',
                'email' => 'farid.dhaffa.musyyafa.te25@stu.pnj.ac.id',
                'no_hp' => '085781098351',
                'jurusan_prodi_kelas' => 'TE/TL/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fathir Azam Zahran',
                'email' => 'fathir.azam.zahran.tm25@stu.pnj.ac.id',
                'no_hp' => '085198653324',
                'jurusan_prodi_kelas' => 'TM/TM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fauzi ramadhan',
                'email' => 'fauzi.ramadhan.te25@stu.pnj.ac.id',
                'no_hp' => '081398799729',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fawwaz Faishal Alwan',
                'email' => 'fawwaz.faishal.alwan.te25@stu.pnj.ac.id',
                'no_hp' => '08558576272',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Felisha Putri Ardiani',
                'email' => 'felisha.putri.ardiani.te25@stu.pnj.ac.id',
                'no_hp' => '081573014959',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ferdiansyah Dwi Apriliano',
                'email' => 'ferdiansyah.dwi.apriliano.te25@stu.pnj.ac.id',
                'no_hp' => '085892632824',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ferdinan Muhamad Rofik',
                'email' => 'ferdinan.muhamad.rofik.te25@stu.pnj.ac.id',
                'no_hp' => '0895617748598',
                'jurusan_prodi_kelas' => 'TE/TOLI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ghaisan Adiend Fathan Al Adli',
                'email' => 'ghaisan.adiend.fathan.al.adli.te25@stu.pnj.ac.id',
                'no_hp' => '088213623917',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Hadzoti Fawwaz Azifa',
                'email' => 'hadzoti.fawwaz.azifa.te24@stu.pnj.ac.id',
                'no_hp' => '0895396200981',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Haikal Ahmad Ardiansyah',
                'email' => 'haikal.ahmad.ardiansyah.te25@stu.pnj.ac.id',
                'no_hp' => '081314374828',
                'jurusan_prodi_kelas' => 'TE/BM/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Hapriyan alamsyha',
                'email' => 'hapriyan.alamsyah.te23@stu.pnj.ac.id',
                'no_hp' => '085773280801',
                'jurusan_prodi_kelas' => 'TE/IKI/6A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Hasbi Ro\'uf Rabbani',
                'email' => 'hasbi.ro.uf.rabbani.te25@stu.pnj.ac.id',
                'no_hp' => '085770838987',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Huldi',
                'email' => 'huldi.te24@stu.pnj.ac.id',
                'no_hp' => '087878601904',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'I Gusti Agung Arya Wirapati RS',
                'email' => 'i.gusti.agung.arya.wirapati.rs.te25@stu.pnj.ac.id',
                'no_hp' => '08561391918',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ibni Aqhibil Apta Putera',
                'email' => 'ibni.aqhibil.apta.putera.te24@stu.pnj.ac.id',
                'no_hp' => '081381002078',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ihsanullintang Sanjoyo',
                'email' => 'ihsanullintang.sanjoyo.te25@stu.pnj.ac.id',
                'no_hp' => '083899436099',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Imam Adli Achsani Nugrohk',
                'email' => 'imam.adli.achsani.nugroho.te25@stu.pnj.ac.id',
                'no_hp' => '085175049525',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Jasim muhammad rafif',
                'email' => 'jasim.muhammad.rafif.te25@stu.pnj.ac.id',
                'no_hp' => '082298021847',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Jihad Al Fath',
                'email' => 'jihadsch1@gmail.com',
                'no_hp' => '089662719963',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Jihad Masyahadad',
                'email' => 'jihad.masyahadad.te25@stu.pnj.ac.id',
                'no_hp' => '081364899841',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Juan Carlos Gea',
                'email' => 'juan.carlos.gea.tik25@stu.pnj.ac.id',
                'no_hp' => '081410180810',
                'jurusan_prodi_kelas' => 'TIK/TMJ/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Julian Fadel Yasin',
                'email' => 'julian.fadel.yasin.te23@stu.pnj.ac.id',
                'no_hp' => '081285263414',
                'jurusan_prodi_kelas' => 'TE/IKI/6B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Kayla Margareth M N',
                'email' => 'kayla.margareth.merdekawati.nababan.te25@stu.pnj.ac.id',
                'no_hp' => '085892064645',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Kessa Putra Anggalaksana',
                'email' => 'kessa.putra.anggalaksana.te23@stu.pnj.ac.id',
                'no_hp' => '081290141773',
                'jurusan_prodi_kelas' => 'TE/IKI/6A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'khairul ikhsan',
                'email' => 'khairul.ikhsan.te25@stu.pnj.ac.id',
                'no_hp' => '088975794149',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Khalid Adyatma',
                'email' => 'khalid.adyatma.te25@stu.pnj.ac.id',
                'no_hp' => '085714612817',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Khanaya Audina Permadi',
                'email' => 'khanaya.audina.permadi.ak25@stu.pnj.ac.id',
                'no_hp' => '081283568668',
                'jurusan_prodi_kelas' => 'TAK/BKT/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Kreshna Wibowo',
                'email' => 'kreshna.wibowo.te24@stu.pnj.ac.id',
                'no_hp' => '082122850682',
                'jurusan_prodi_kelas' => 'TE/TT/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Lavanya Azka Fadilah',
                'email' => 'lavanya.azka.fadilah.te25@stu.pnj.ac.id',
                'no_hp' => '085288039826',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Lidia Tri Ratnasari',
                'email' => 'lidia.tri.ratnasari.ak25@stu.pnj.ac.id',
                'no_hp' => '0895365153872',
                'jurusan_prodi_kelas' => 'TAK/BKT/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Marta Fransiska Eufrasia',
                'email' => 'marta.fransiska.eufrasia.te25@stu.pnj.ac.id',
                'no_hp' => '0895340382437',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Masagus Ihsan Farizqy',
                'email' => 'masagus.ihsan.farizqy.te25@stu.pnj.ac.id',
                'no_hp' => '08111924638',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Maulana Rafly Abdullah',
                'email' => 'maulana.rafly.abdullah.te25@stu.pnj.ac.id',
                'no_hp' => '085150585256',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Maulana Zharif Arkan',
                'email' => 'maulana.zharif.arkan.te25@stu.pnj.ac.id',
                'no_hp' => '081210417123',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Mohamad Malik Fadillah Arwin',
                'email' => 'mohamad.malik.fadillah.arwin.tik25@stu.pnj.ac.id',
                'no_hp' => '089512264970',
                'jurusan_prodi_kelas' => 'TIK/TI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muflih Nabil Aziz',
                'email' => 'muflih.nabil.aziz.te25@stu.pnj.ac.id',
                'no_hp' => '082226122621',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhamad Al Farisi',
                'email' => 'muhamad.al.farisi.te25@stu.pnj.ac.id',
                'no_hp' => '082133356934',
                'jurusan_prodi_kelas' => 'TE/BM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhamad Rizhan Faturahman',
                'email' => 'muhamad.rizhan.faturahman.te25@stu.pnj.ac.id',
                'no_hp' => '085776504819',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhamad Rizki Sabri',
                'email' => 'muhamad.rizki.sabri.te25@stu.pnj.ac.id',
                'no_hp' => '085888691962',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhamad safarul fajar',
                'email' => 'muhamad.safarul.fajar.tm25@stu.pnj.ac.id',
                'no_hp' => '089643035914',
                'jurusan_prodi_kelas' => 'TM/TM/2E',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Abdillah Syaiban',
                'email' => 'abdillahsyaiban@gmail.com',
                'no_hp' => '081545873593',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Abyan Kaafiy',
                'email' => 'muhammad.abyan.kaafiy.te25@stu.pnj.ac.id',
                'no_hp' => '08561619293',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Addien Fikrul Akbar',
                'email' => 'muhammad.addien.fikrul.akbar.te25@stu.pnj.ac.id',
                'no_hp' => '085545132710',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Adnan Hafiz',
                'email' => 'adnan.hafiz217@gmail.com',
                'no_hp' => '087885802757',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Alfatih Sulaeman',
                'email' => 'muhammad.alfatih.sulaeman.te25@stu.pnj.ac.id',
                'no_hp' => '087792130683',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Dzaki Hisyam',
                'email' => 'muhammad.dzaki.hisyam.te25@stu.pnj.ac.id',
                'no_hp' => '0895326118443',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Fadlan Kamil',
                'email' => 'muhammad.fadlan.kamil.te25@stu.pnj.ac.id',
                'no_hp' => '081211902966',
                'jurusan_prodi_kelas' => 'TE/BM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Fahrul Rizal Rahman',
                'email' => 'muhammad.fahrul.rizal.rahman.te23@stu.pnj.ac.id',
                'no_hp' => '088801248606',
                'jurusan_prodi_kelas' => 'TE/IKI/6A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Faiq Satia Prasaja',
                'email' => 'muhammad.faiq.satia.prasaja.te25@stu.pnj.ac.id',
                'no_hp' => '085894661380',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Faiz An Naafi',
                'email' => 'muhammad.faiz.an.naafi.te25@stu.pnj.ac.id',
                'no_hp' => '082162647180',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Fakhri Rossi',
                'email' => 'muhammad.fakhri.rossi.te25@stu.pnj.ac.id',
                'no_hp' => '081391445470',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Fakhriansyah',
                'email' => 'muhammad.fakhriansyah.te23@stu.pnj.ac.id',
                'no_hp' => '081212520223',
                'jurusan_prodi_kelas' => 'TE/IKI/6B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Fakih Nur Muzakki',
                'email' => 'muhammad.fakih.nur.muzakki.te25@stu.pnj.ac.id',
                'no_hp' => '081282050427',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'MUHAMMAD FARHAN ABDULLAH',
                'email' => 'muhammad.farhan.abdullah.te25@stu.pnj.ac.id',
                'no_hp' => '085649033609',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Farrel Baddar Pamuji',
                'email' => 'muhammad.farrel.baddar.pamuji.te25@stu.pnj.ac.id',
                'no_hp' => '081387032739',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Firas Alhamra',
                'email' => 'alhamrafiras18@gmail.com',
                'no_hp' => '085782265008',
                'jurusan_prodi_kelas' => 'TM/ME/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Hafizh',
                'email' => 'muhammad.hafizh.tik25@stu.pnj.ac.id',
                'no_hp' => '089529015149',
                'jurusan_prodi_kelas' => 'TIK/TMJ/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Hilmy Aulya Rahman',
                'email' => 'muhammad.hilmy.aulya.rahman.te23@stu.pnj.ac.id',
                'no_hp' => '085693708137',
                'jurusan_prodi_kelas' => 'TE/IKI/6A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Ibnu Aqil',
                'email' => 'muhammad.ibnu.aqil.te25@stu.pnj.ac.id',
                'no_hp' => '081287113690',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Ichban Ramdhani',
                'email' => 'muhammad.ichban.ramdhani.tm25@stu.pnj.ac.id',
                'no_hp' => '082124867828',
                'jurusan_prodi_kelas' => 'TM/TM/2F',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Ihsan',
                'email' => 'muhammad.ihsan.te24@stu.pnj.ac.id',
                'no_hp' => '085692110774',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Iqbal',
                'email' => 'iqbalmuhammad283732@gmail.com',
                'no_hp' => '081573222072',
                'jurusan_prodi_kelas' => 'TM/TM/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Irshad Al Faqih',
                'email' => 'muhammad.irshad.al.faqih.te25@stu.pnj.ac.id',
                'no_hp' => '081318477235',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Lutfi Firmansyah',
                'email' => 'muhammad.lutfi.firmansyah.te25@stu.pnj.ac.id',
                'no_hp' => '085604088709',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Luthfi',
                'email' => 'muhammad.luthfi.te25@stu.pnj.ac.id',
                'no_hp' => '088808992133',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Nabil',
                'email' => 'arkansimdigei1@gmail.com',
                'no_hp' => '089510130247',
                'jurusan_prodi_kelas' => 'TAK/BKT/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Nabil Habibie',
                'email' => 'muhammad.nabil.habibie.te25@stu.pnj.ac.id',
                'no_hp' => '081385896025',
                'jurusan_prodi_kelas' => 'TE/BM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'MUHAMMAD NANDANA NATHAN',
                'email' => 'muhammad.nandana.nathan.tm25@stu.pnj.ac.id',
                'no_hp' => '087890599921',
                'jurusan_prodi_kelas' => 'TM/TM/2E',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Naufal Halim',
                'email' => 'muhammad.naufal.halim.te25@stu.pnj.ac.id',
                'no_hp' => '08997445420',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Raditya',
                'email' => 'muhamad.raditya.tm25@stu.pnj.ac.id',
                'no_hp' => '089668756791',
                'jurusan_prodi_kelas' => 'TM/TRM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Rafi Firmansyah',
                'email' => 'muhammad.rafi.firmansyah.te24@stu.pnj.ac.id',
                'no_hp' => '08567314315',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Raihan Fadhilah',
                'email' => 'muhammad.raihan.fadhilah.te25@stu.pnj.ac.id',
                'no_hp' => '087821050337',
                'jurusan_prodi_kelas' => 'TE/BM/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Rashya Erlangga',
                'email' => 'muhammad.rashya.erlangga.te25@stu.pnj.ac.id',
                'no_hp' => '085813920228',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Muhammad Tahadj Priyoutomo',
                'email' => 'muhammad.tahadj.priyoutomo.te24@stu.pnj.ac.id',
                'no_hp' => '085156564645',
                'jurusan_prodi_kelas' => 'TE/TT/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'MUHMAMMAD RIZKI RAMADHANI',
                'email' => 'rizkiramadhani7718@gmail.com',
                'no_hp' => '081915235774',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Musthafa Hadji',
                'email' => 'musthafa.hadji.te25@stu.pnj.ac.id',
                'no_hp' => '085210508257',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Mutiara Bunga Rianti',
                'email' => 'mutiara.bunga.rianti.tm25@stu.pnj.ac.id',
                'no_hp' => '089509602403',
                'jurusan_prodi_kelas' => 'TM/TRKE/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Najwa Sharfina Muswar',
                'email' => 'najwa.sharfina.muswar.te25@stu.pnj.ac.id',
                'no_hp' => '082125514047',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Naufal Hakim Salik',
                'email' => 'naufal.hakim.salik.te25@stu.pnj.ac.id',
                'no_hp' => '081389563312',
                'jurusan_prodi_kelas' => 'TE/BM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Nayla Fitriani',
                'email' => 'nayla.fitriani.te24@stu.pnj.ac.id',
                'no_hp' => '087883559021',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Nazwaini',
                'email' => 'nazwaini.te24@stu.pnj.ac.id',
                'no_hp' => '085814928958',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'NISRINA TALITA KARIB',
                'email' => 'nisrina.talita.karib.te25@stu.pnj.ac.id',
                'no_hp' => '082123067963',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Pasha Pratama',
                'email' => 'pasha.pratama.te25@stu.pnj.ac.id',
                'no_hp' => '087747834023',
                'jurusan_prodi_kelas' => 'TE/TT/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Putra Nur Pratama',
                'email' => 'putra.nur.pratama.tik25@stu.pnj.ac.id',
                'no_hp' => '085283778120',
                'jurusan_prodi_kelas' => 'TM/TMJ/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Rafly Muhammad Zaky',
                'email' => 'rafly.muhammad.zaky.te25@stu.pnj.ac.id',
                'no_hp' => '085795217866',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Raka Arkana Fiery',
                'email' => 'raka.arkana.fiery.te24@stu.pnj.ac.id',
                'no_hp' => '08159409229',
                'jurusan_prodi_kelas' => 'TE/TT/4B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ramzhaniy Ardhan Narendra',
                'email' => 'ramzhaniy.ardhan.narendra.te25@stu.pnj.ac.id',
                'no_hp' => '081316840674',
                'jurusan_prodi_kelas' => 'TE/TL/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Rangga Putra Ramadhan',
                'email' => 'rangga.putra.ramadhan.te25@stu.pnj.ac.id',
                'no_hp' => '08973743562',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Rara Areta Bathari Isa',
                'email' => 'rara.areta.bathari.isa.te25@stu.pnj.ac.id',
                'no_hp' => '081318562007',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Rasya Tri Aditya',
                'email' => 'rasya.tri.aditya.te25@stu.pnj.ac.id',
                'no_hp' => '085782506218',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ratumas Sucihaawwaa',
                'email' => 'rciawaratucici@gmail.com',
                'no_hp' => '085811083607',
                'jurusan_prodi_kelas' => 'TE/BM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Rayhan Fachreza',
                'email' => 'rayhan.fachreza.te25@stu.pnj.ac.id',
                'no_hp' => '085693697590',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Rico Agustian Baringbing',
                'email' => 'ricobaringbing187@gmail.com',
                'no_hp' => '085311629544',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ridhwan Hafidzun Alim',
                'email' => 'ridhwan.hafidzun.alim.te24@stu.pnj.ac.id',
                'no_hp' => '081281222450',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Riski Febriyan',
                'email' => 'riski.febriyan.te25@stu.pnj.ac.id',
                'no_hp' => '087734290198',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ruh Setojati',
                'email' => 'ruh.setojati.te24@stu.pnj.ac.id',
                'no_hp' => '087812282069',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Ryan',
                'email' => 'ryan.te25@stu.pnj.ac.id',
                'no_hp' => '087763541091',
                'jurusan_prodi_kelas' => 'TE/IKI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Sabrina Vinca Az-Zahra',
                'email' => 'sabrina.vinca.azzahra.te25@stu.pnj.ac.id',
                'no_hp' => '08975914646',
                'jurusan_prodi_kelas' => 'TE/IKI/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Safana Fuadah Azzahra',
                'email' => 'safana.fuadah.azzahra.te25@stu.pnj.ac.id',
                'no_hp' => '085716272585',
                'jurusan_prodi_kelas' => 'TE/EC/2D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Shafura Kasyful Haq',
                'email' => 'shafura.kasyful.haq.te24@stu.pnj.ac.id',
                'no_hp' => '081314398606',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Syifa Kalilah',
                'email' => 'syifa.kalilah.an24@stu.pnj.ac.id',
                'no_hp' => '081283404020',
                'jurusan_prodi_kelas' => 'AN/ABT/4C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Syifa Nur Jauzah',
                'email' => 'syifanurjauzah@gmail.com',
                'no_hp' => '089514456843',
                'jurusan_prodi_kelas' => 'TIK/TI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Teuku Naufal Abyan',
                'email' => 'teuku.naufal.abyan.te25@stu.pnj.ac.id',
                'no_hp' => '081297616225',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Thaufik Jonatan Bagaskara',
                'email' => 'thaufik.jonatan.bagaskara.te25@stu.pnj.ac.id',
                'no_hp' => '085161361606',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Umar Fadzli Santoso',
                'email' => 'umar.fadzli.santoso.te25@stu.pnj.ac.id',
                'no_hp' => '082125712676',
                'jurusan_prodi_kelas' => 'TE/TOLI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'William Abraham ButarButar',
                'email' => 'william.abraham.butarbutar.te25@stu.pnj.ac.id',
                'no_hp' => '085697869179',
                'jurusan_prodi_kelas' => 'TE/EC/2B',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Wulan Tiara Kasih',
                'email' => 'wulan.tiara.kasih.te25@stu.pnj.ac.id',
                'no_hp' => '085156877161',
                'jurusan_prodi_kelas' => 'TE/EC/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Yazid Yusuf',
                'email' => 'yazid.yusuf.tik25@stu.pnj.ac.id',
                'no_hp' => '085161661805',
                'jurusan_prodi_kelas' => 'TIK/TI/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Yuan Rizqy Pratama',
                'email' => 'yuan.rizqy.pratama.te25@stu.pnj.ac.id',
                'no_hp' => '083808058849',
                'jurusan_prodi_kelas' => 'TE/EC/2C',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Zahra Aulia Nila Pramesti',
                'email' => 'zahra.aulia.nila.pramesti.tm25@stu.pnj.ac.id',
                'no_hp' => '0895411938783',
                'jurusan_prodi_kelas' => 'TM/TRM/2A',
                'id_department' => '0',
                'nama_jabatan' => 'anggota',
            ],
            [
                'nama_lengkap' => 'Fahmi Ibrahim',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '1',
                'nama_jabatan' => 'Wakil Ketua',
            ],
            [
                'nama_lengkap' => 'Muhammad Syafiq Aziz',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '1',
                'nama_jabatan' => 'Ketua',
            ],
            [
                'nama_lengkap' => 'Dian Bestari',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TIK/TMD/4A',
                'id_department' => '2',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Mutiya Laila Fitri',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/BM/4A',
                'id_department' => '2',
                'nama_jabatan' => 'Kepala Department',
            ],
            [
                'nama_lengkap' => 'Beryl Ghanim Setiyoko',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '3',
                'nama_jabatan' => 'Kepala Department',
            ],
            [
                'nama_lengkap' => 'David Vernando Hutagalung',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '3',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Ajeng Nur Azizah',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Dyo putra mulya',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Elvina Naira Safitri',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Isnursyah Yudha Prawira',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '4',
                'nama_jabatan' => 'Kepala Department',
            ],
            [
                'nama_lengkap' => 'Kiki Amaliasari Ahmad',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Ilsya nur abika',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Muhammad Ari Mahesa',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/TOLI/4A',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Nazarudin Zidan',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Qessar Philoice Raja Pandia',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '4',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Abdul Latif',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Arsa Danish Fadillah',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Daffa Firmansyah',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Diaz Marcelo Firman Gandi',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4C',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Faiz Dwi Jatnika',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TM/TRM/4B',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Fatih Ahmad Ridho',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TM/TRM/4B',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Firhan Maulana Sopian',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/TOLI/4A',
                'id_department' => '5',
                'nama_jabatan' => 'Kepala Department',
            ],
            [
                'nama_lengkap' => 'Mohammad Bintang Satya Guna',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TM/TM/MPRN4A',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Muhammad Haikal',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4C',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Muhammad Ikhwanul Muslim',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Putrama Abi Aryasatya',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Rakha Alif Ibrahim',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '5',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Azhar Al Bana',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Dimas Surya Saputra',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/TT/4D',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Haamiim Muhammad Al Fath',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Hanif Ramdhan',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4B',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Ibrahim',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '6',
                'nama_jabatan' => 'Kepala Department',
            ],
            [
                'nama_lengkap' => 'Iqbal Jati Djatiran',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Leonardus Alvin Natanael Dappa',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Mochamad Aqil Maulana rais',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TM/TM/4E',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Muhammad Rafli Az-Zikri',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Rizqi Cahya Ramadhan',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4A',
                'id_department' => '6',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Ali Fari Fakhrozi',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4A',
                'id_department' => '7',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Arif Fahmi Abdillah',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '7',
                'nama_jabatan' => 'Kepala Department',
            ],
            [
                'nama_lengkap' => 'Dhika Adiansyah',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TM/ME/4D',
                'id_department' => '7',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Hasna Khaira Pramudianto',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'AK/AKT/4B',
                'id_department' => '7',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Illbe Jihadin Wilen',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/TOLI/4A',
                'id_department' => '7',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Jeremy Matthew Sejati',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/EC/4D',
                'id_department' => '7',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Muhammad Mufid',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '7',
                'nama_jabatan' => 'Staff',
            ],
            [
                'nama_lengkap' => 'Pandu Muhamad Fazri',
                'email' => '',
                'no_hp' => '',
                'jurusan_prodi_kelas' => 'TE/IKI/4B',
                'id_department' => '7',
                'nama_jabatan' => 'Staff',
            ],
        ];

        foreach ($recruitmentData as $recruitment) {
            // Determine jenis_oprec based on nama_jabatan
            $jenisOprec = ($recruitment['nama_jabatan'] === 'anggota') ? 'anggota' : 'pengurus';

            DB::table('open_recruitment')->insert([
                'id_tahun' => 1,
                'nama_lengkap' => $recruitment['nama_lengkap'],
                'email' => $recruitment['email'],
                'no_hp' => $recruitment['no_hp'],
                'jurusan_prodi_kelas' => $recruitment['jurusan_prodi_kelas'],
                'id_department' => $recruitment['id_department'],
                'nama_jabatan' => $recruitment['nama_jabatan'],
                'jenis_oprec' => $jenisOprec,
                'status_seleksi' => 'lulus',
            ]);
        }
    }
}
